In [157]:
import yfinance as yf
ticker = yf.Ticker("AAPL")
dict(ticker.fast_info)

{'currency': 'USD',
 'dayHigh': 336.2200012207031,
 'dayLow': 326.29998779296875,
 'exchange': 'NMS',
 'fiftyDayAverage': 317.97419982910156,
 'lastPrice': 332.2699890136719,
 'lastVolume': 50659000,
 'marketCap': 4849208028263.55,
 'open': 327.45001220703125,
 'previousClose': 325.7986,
 'quoteType': 'EQUITY',
 'regularMarketPreviousClose': 326.57000732421875,
 'shares': 14594180000,
 'tenDayAverageVolume': 46545660,
 'threeMonthAverageVolume': 53812387,
 'timezone': 'America/New_York',
 'twoHundredDayAverage': 284.9533494567871,
 'yearChange': 0.4037600054820762,
 'yearHigh': 344.57000732421875,
 'yearLow': 235.02999877929688}

In [158]:
ticker.history(
            period="1mo",
            interval="1h")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2026-08-12 09:30:00-04:00,305.130005,305.660004,302.179993,302.345001,7719258,0.0,0.0
2026-08-12 10:30:00-04:00,302.359985,303.190002,301.029999,301.079987,4848995,0.0,0.0
2026-08-12 11:30:00-04:00,301.089905,301.820007,300.570007,301.510010,3572317,0.0,0.0
2026-08-12 12:30:00-04:00,301.515015,302.510010,301.410004,302.160095,2585592,0.0,0.0
2026-08-12 13:30:00-04:00,302.170013,302.297699,301.059998,301.125000,3113898,0.0,0.0
...,...,...,...,...,...,...,...
2026-09-11 11:30:00-04:00,335.540009,335.540009,333.630005,334.170013,4739878,0.0,0.0
2026-09-11 12:30:00-04:00,334.190002,334.850006,333.829987,333.950012,2580323,0.0,0.0
2026-09-11 13:30:00-04:00,333.959991,334.299988,332.549988,332.855011,3573189,0.0,0.0
2026-09-11 14:30:00-04:00,332.859985,333.178986,332.390015,332.640106,4162608,0.0,0.0
2026-09-11 15:30:00-04:00,332.679993,333.070007,332.070007,332.230011,3626964,0.0,0.0

In [159]:
ticker.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allows customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'Executive Chairman of the Board',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. John  Ternus',
   'age': 49,
   'title': 'CEO & Director',
   'yearBorn': 1976,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 55,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1970,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 6,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1788220800,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 326.57,
 'open': 327.63,
 'dayLow': 326.3,
 'dayHigh': 336.22,
 'regularMarketPreviousClose': 326.57,
 'regularMarketOpen': 327.63,
 'regularMarketDayLow': 326.3,
 'regularMarketDayHigh': 336.22,
 'dividendRate': 1.08,
 'dividendYield': 0.33,
 'exDividendDate': 1786320000,
 'payoutRatio': 0.1204,
 'fiveYearAvgDividendYield': 0.5,
 'beta': 1.085,
 'trailingPE': 38.148106,
 'forwardPE': 34.703167,
 'volume': 50423955,
 'regularMarketVolume': 50423955,
 'averageVolume': 54055456,
 'averageVolume10days': 46545660,
 'averageDailyVolume10Day': 46545660,
 'bid': 332.48,
 'ask': 333.97,
 'bidSize': 3,
 'askSize': 4,
 'marketCap': 4849207869440,
 'nonDilutedMarketCap': 4849208188600,
 'fiftyTwoWeekLow': 235.03,
 'fiftyTwoWeekHigh': 344.57,
 'allTimeHigh': 344.57,
 'allTimeLow': 0.049107,
 'fulldayPrice': 332.55,
 'fulldayChange': 5.69998,
 'fulldayChangePercent': 1.74541,
 'priceToSalesTrailing12Months': 10.38768,
 'fiftyDayAverage': 317.9742,
 'twoHundredDayAverage': 284.95334,
 'trailingAnnualDividendRate': 1.05,
 'trailingAnnualDividendYield': 0.003215237,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4871152992256,
 'profitMargins': 0.27618998,
 'floatShares': 14569078010,
 'sharesOutstanding': 14594180000,
 'sharesShort': 139749097,
 'sharesShortPriorMonth': 141606163,
 'sharesShortPreviousMonthDate': 1785456000,
 'dateShortInterest': 1788134400,
 'sharesPercentSharesOut': 0.0095999995,
 'heldPercentInsiders': 0.01648,
 'heldPercentInstitutions': 0.66336995,
 'shortRatio': 2.97,
 'shortPercentOfFloat': 0.0095999995,
 'impliedSharesOutstanding': 14594180000,
 'bookValue': 7.36,
 'priceToBook': 45.14538,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1782518400,
 'earningsQuarterlyGrowth': 0.271,
 'netIncomeToCommon': 128929996800,
 'trailingEps': 8.71,
 'forwardEps': 9.57463,
 'pegRatio': 2.48,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 10.435,
 'enterpriseToEbitda': 29.002,
 '52WeekChange': 0.40376008,
 'SandP52WeekChange': 0.1574688,
 'lastDividendValue': 0.27,
 'lastDividendDate': 1786320000,
 'quoteType': 'EQUITY',
 'currentPrice': 332.27,
 'targetHighPrice': 400.0,
 'targetLowPrice': 215.0,
 'targetMeanPrice': 324.40155,
 'targetMedianPrice': 335.0,
 'recommendationMean': 2.18182,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 39,
 'totalCash': 62399000576,
 'totalCashPerShare': 4.276,
 'ebitda': 167959003136,
 'totalDebt': 84343996416,
 'quickRatio': 0.812,
 'currentRatio': 1.003,
 'totalRevenue': 466822987776,
 'debtToEquity': 78.445,
 'revenuePerShare': 31.707,
 'returnOnAssets': 0.27082002,
 'returnOnEquity': 1.4875101,
 'grossProfits': 227123003392,
 'freeCashflow': 107721875456,
 'operatingCashflow': 146723995648,
 'earningsGrowth': 0.287,
 'revenueGrowth': 0.164,
 'grossMargins': 0.48653,
 'ebitdaMargins': 0.35979,
 'operatingMargins': 0.32623002,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'CLOSED',
 'corporateActions': [],
 'postMarketTime': 1789171199,
 'regularMarketTime': 1789156801,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 1.74541,
 'regularMarketPrice': 332.27,
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'postMarketChangePercent': 0.08426845,
 'postMarketPrice': 332.55,
 'postMarketChange': 0.27999878,
 'regularMarketChange': 5.69998,
 'regularMarketDayRange': '326.3 - 336.22',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 54055456,
 'fiftyTwoWeekLowChange': 97.23999,
 'fiftyTwoWeekLowChangePercent': 0.41373438,
 'fiftyTwoWeekRange': '235.03 - 344.57',
 'fiftyTwoWeekHighChange': -12.300018,
 'fiftyTwoWeekHighChangePercent': -0.03569672,
 'fiftyTwoWeekChangePercent': 40.376007,
 'dividendDate': 1786579200,
 'earningsTimestamp': 1785441600,
 'earningsTimestampStart': 1793304000,
 'earningsTimestampEnd': 1793304000,
 'earningsCallTimestampStart': 1785441600,
 'earningsCallTimestampEnd': 1785441600,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 8.71,
 'epsForward': 9.57463,
 'epsCurrentYear': 8.82929,
 'priceEpsCurrentYear': 37.632694,
 'fiftyDayAverageChange': 14.295776,
 'fiftyDayAverageChangePercent': 0.044958916,
 'twoHundredDayAverageChange': 47.31665,
 'twoHundredDayAverageChangePercent': 0.16605052,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.2 - Buy',
 'cryptoTradeable': False,
 'displayName': 'Apple',
 'trailingPegRatio': 2.6068}

In [160]:
ticker.financials

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Tax Rate For Calcs,1.560000e-01,2.410000e-01,1.470000e-01,1.620000e-01,NaN
Normalized EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
Net Income From Continuing Operation Net Minority Interest,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Reconciled Depreciation,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10,NaN
Reconciled Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
EBIT,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Net Interest Income,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Normalized Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income From Continuing And Discontinued Operation,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Total Expenses,2.831110e+11,2.678190e+11,2.689840e+11,2.748910e+11,NaN
Total Operating Income As Reported,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Diluted Average Shares,1.500470e+10,1.540810e+10,1.581255e+10,1.632582e+10,NaN
Basic Average Shares,1.494850e+10,1.534378e+10,1.574423e+10,1.621596e+10,NaN
Diluted EPS,7.460000e+00,6.080000e+00,6.130000e+00,6.110000e+00,NaN
Basic EPS,7.490000e+00,6.110000e+00,6.160000e+00,6.150000e+00,NaN
Diluted NI Availto Com Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Common Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Including Noncontrolling Interests,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Continuous Operations,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Tax Provision,2.071900e+10,2.974900e+10,1.674100e+10,1.930000e+10,NaN
Pretax Income,1.327290e+11,1.234850e+11,1.137360e+11,1.191030e+11,NaN
Other Income Expense,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Other Non Operating Income Expenses,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Net Non Operating Interest Income Expense,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense Non Operating,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income Non Operating,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Operating Income,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Operating Expense,6.215100e+10,5.746700e+10,5.484700e+10,5.134500e+10,NaN
Research And Development,3.455000e+10,3.137000e+10,2.991500e+10,2.625100e+10,NaN
Selling General And Administration,2.760100e+10,2.609700e+10,2.493200e+10,2.509400e+10,NaN
Gross Profit,1.952010e+11,1.806830e+11,1.691480e+11,1.707820e+11,NaN
Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
Total Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN
Operating Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN

In [161]:
ticker.quarterly_financials

,2026-06-30,2026-03-31,2025-12-31,2025-09-30,2025-06-30
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Rate For Calcs,1.786200e-01,1.750000e-01,1.750000e-01,1.627240e-01,1.639970e-01
Normalized EBITDA,3.901500e+10,3.932400e+10,5.406600e+10,3.555400e+10,3.103200e+10
Net Income From Continuing Operation Net Minority Interest,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Reconciled Depreciation,3.320000e+09,3.439000e+09,3.214000e+09,3.127000e+09,2.830000e+09
Reconciled Cost Of Revenue,5.464700e+10,5.640300e+10,7.452500e+10,5.412500e+10,5.031800e+10
EBITDA,3.901500e+10,3.932400e+10,5.406600e+10,3.555400e+10,3.103200e+10
EBIT,3.569500e+10,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10
Normalized Income,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Net Income From Continuing And Discontinued Operation,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Total Expenses,7.372200e+10,7.529900e+10,9.290400e+10,7.003900e+10,6.583400e+10
Total Operating Income As Reported,3.569500e+10,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10
Diluted Average Shares,1.471468e+10,1.472587e+10,1.481036e+10,1.486361e+10,1.494818e+10
Basic Average Shares,1.465611e+10,1.467328e+10,1.474816e+10,1.481531e+10,1.490289e+10
Diluted EPS,2.020000e+00,2.010000e+00,2.840000e+00,1.850000e+00,1.570000e+00
Basic EPS,2.030000e+00,2.020000e+00,2.850000e+00,1.850000e+00,1.570000e+00
Diluted NI Availto Com Stockholders,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Net Income Common Stockholders,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Net Income,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Net Income Including Noncontrolling Interests,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Net Income Continuous Operations,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Tax Provision,6.478000e+09,6.255000e+09,8.905000e+09,5.338000e+09,4.597000e+09
Pretax Income,3.626700e+10,3.583300e+10,5.100200e+10,3.280400e+10,2.803100e+10
Other Income Expense,5.720000e+08,-5.200000e+07,1.500000e+08,3.770000e+08,-1.710000e+08
Other Non Operating Income Expenses,5.720000e+08,-5.200000e+07,1.500000e+08,3.770000e+08,-1.710000e+08
Operating Income,3.569500e+10,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10
Operating Expense,1.907500e+10,1.889600e+10,1.837900e+10,1.591400e+10,1.551600e+10
Research And Development,1.172900e+10,1.141900e+10,1.088700e+10,8.866000e+09,8.866000e+09
Selling General And Administration,7.346000e+09,7.477000e+09,7.492000e+09,7.048000e+09,6.650000e+09
Gross Profit,5.477000e+10,5.478100e+10,6.923100e+10,4.834100e+10,4.371800e+10
Cost Of Revenue,5.464700e+10,5.640300e+10,7.452500e+10,5.412500e+10,5.031800e+10
Total Revenue,1.094170e+11,1.111840e+11,1.437560e+11,1.024660e+11,9.403600e+10
Operating Revenue,1.094170e+11,1.111840e+11,1.437560e+11,1.024660e+11,9.403600e+10

In [162]:
ticker.balance_sheet

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
Treasury Shares Number,NaN,NaN,0.000000e+00,NaN,NaN
Ordinary Shares Number,1.477326e+10,1.511679e+10,1.555006e+10,1.594342e+10,NaN
Share Issued,1.477326e+10,1.511679e+10,1.555006e+10,1.594342e+10,NaN
Net Debt,6.272300e+10,7.668600e+10,8.112300e+10,9.642300e+10,NaN
Total Debt,9.865700e+10,1.066290e+11,1.110880e+11,1.324800e+11,NaN
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,5.469700e+10,6.517100e+10,6.155500e+10,4.830400e+10,NaN
Other Short Term Investments,1.876300e+10,3.522800e+10,3.159000e+10,2.465800e+10,NaN
Cash And Cash Equivalents,3.593400e+10,2.994300e+10,2.996500e+10,2.364600e+10,NaN
Cash Equivalents,7.667000e+09,2.744000e+09,1.606000e+09,5.100000e+09,NaN
Cash Financial,2.826700e+10,2.719900e+10,2.835900e+10,1.854600e+10,NaN

In [163]:
ticker.dividends

Date
1987-05-11 09:30:00-04:00    0.000536
1987-08-10 09:30:00-04:00    0.000536
1987-11-17 09:30:00-05:00    0.000714
1988-02-12 09:30:00-05:00    0.000714
1988-05-16 09:30:00-04:00    0.000714
                               ...
2025-08-11 09:30:00-04:00    0.260000
2025-11-10 09:30:00-05:00    0.260000
2026-02-09 09:30:00-05:00    0.260000
2026-05-11 09:30:00-04:00    0.270000
2026-08-10 09:30:00-04:00    0.270000
Name: Dividends, Length: 92, dtype: float64

In [164]:
ticker.splits

Date
1987-06-16 09:30:00-04:00    2.0
2000-06-21 09:30:00-04:00    2.0
2005-02-28 09:30:00-05:00    2.0
2014-06-09 09:30:00-04:00    7.0
2020-08-31 09:30:00-04:00    4.0
Name: Stock Splits, dtype: float64

In [165]:
import requests
session=requests.Session()
response = session.get(
                f"{"https://data-api.ecb.europa.eu/service/data"}/{"EXR"}/{"M.USD.EUR.SP00.E"}",
                params= {"startPeriod": "2026-01","endPeriod":"2026-02","format": "jsondata"},
                timeout=10)
response.raise_for_status()
response.json()

{'header': {'id': 'bc414474-030b-448f-8c47-83ec484e0a3c',
  'test': False,
  'prepared': '2026-09-12T22:12:29.703+02:00',
  'sender': {'id': 'ECB'}},
 'dataSets': [{'action': 'Replace',
   'validFrom': '2026-09-12T22:12:29.703+02:00',
   'series': {'0:0:0:0:0': {'attributes': [0,
      None,
      0,
      None,
      None,
      None,
      None,
      None,
      None,
      0,
      None,
      None,
      0,
      None,
      0,
      None,
      0,
      0,
      0,
      0],
     'observations': {'0': [1.1919, 0, 0, None, None],
      '1': [1.1805, 0, 0, None, None]}}}}],
 'structure': {'links': [{'title': 'Exchange Rates',
    'rel': 'dataflow',
    'href': 'https://data-api.ecb.europa.eu:443/service/dataflow/ECB/EXR/1.0'}],
  'name': 'Exchange Rates',
  'dimensions': {'series': [{'id': 'FREQ',
     'name': 'Frequency',
     'values': [{'id': 'M', 'name': 'Monthly'}]},
    {'id': 'CURRENCY',
     'name': 'Currency',
     'values': [{'id': 'USD', 'name': 'US dollar'}]},
    {'id': 'CURRENCY_DENOM',
     'name': 'Currency denominator',
     'values': [{'id': 'EUR', 'name': 'Euro'}]},
    {'id': 'EXR_TYPE',
     'name': 'Exchange rate type',
     'values': [{'id': 'SP00', 'name': 'Spot'}]},
    {'id': 'EXR_SUFFIX',
     'name': 'Series variation - EXR context',
     'values': [{'id': 'E', 'name': 'End-of-period'}]}],
   'observation': [{'id': 'TIME_PERIOD',
     'name': 'Time period or range',
     'role': 'time',
     'values': [{'id': '2026-01',
       'name': '2026-01',
       'start': '2026-01-01T00:00:00.000+01:00',
       'end': '2026-01-31T23:59:59.999+01:00'},
      {'id': '2026-02',
       'name': '2026-02',
       'start': '2026-02-01T00:00:00.000+01:00',
       'end': '2026-02-28T23:59:59.999+01:00'}]}]},
  'attributes': {'series': [{'id': 'TIME_FORMAT',
     'name': 'Time format code',
     'values': [{'name': 'P1M'}]},
    {'id': 'BREAKS', 'name': 'Breaks', 'values': []},
    {'id': 'COLLECTION',
     'name': 'Collection indicator',
     'values': [{'id': 'E', 'name': 'End of period'}]},
    {'id': 'COMPILING_ORG', 'name': 'Compiling organisation', 'values': []},
    {'id': 'DISS_ORG',
     'name': 'Data dissemination organisation',
     'values': []},
    {'id': 'DOM_SER_IDS', 'name': 'Domestic series ids', 'values': []},
    {'id': 'PUBL_ECB', 'name': 'Source publication (ECB only)', 'values': []},
    {'id': 'PUBL_MU',
     'name': 'Source publication (Euro area only)',
     'values': []},
    {'id': 'PUBL_PUBLIC', 'name': 'Source publication (public)', 'values': []},
    {'id': 'UNIT_INDEX_BASE',
     'name': 'Unit index base',
     'values': [{'name': '99Q1=100'}]},
    {'id': 'COMPILATION', 'name': 'Compilation', 'values': []},
    {'id': 'COVERAGE', 'name': 'Coverage', 'values': []},
    {'id': 'DECIMALS',
     'name': 'Decimals',
     'values': [{'id': '4', 'name': 'Four'}]},
    {'id': 'NAT_TITLE', 'name': 'National language title', 'values': []},
    {'id': 'SOURCE_AGENCY',
     'name': 'Source agency',
     'values': [{'id': '4F0', 'name': 'European Central Bank (ECB)'}]},
    {'id': 'SOURCE_PUB', 'name': 'Publication source', 'values': []},
    {'id': 'TITLE',
     'name': 'Title',
     'values': [{'name': 'US dollar/Euro ECB reference exchange rate'}]},
    {'id': 'TITLE_COMPL',
     'name': 'Title complement',
     'values': [{'name': 'ECB reference exchange rate, US dollar/Euro, 2.15 pm (C.E.T.)'}]},
    {'id': 'UNIT',
     'name': 'Unit',
     'values': [{'id': 'USD', 'name': 'US dollar'}]},
    {'id': 'UNIT_MULT',
     'name': 'Unit multiplier',
     'values': [{'id': '0', 'name': 'Units'}]}],
   'observation': [{'id': 'OBS_STATUS',
     'name': 'Observation status',
     'values': [{'id': 'A', 'name': 'Normal value'}]},
    {'id': 'OBS_CONF',
     'name': 'Observation confidentiality',
     'values': [{'id': 'F', 'name': 'Free'}]},
    {'id': 'OBS_PRE_BREAK',
     'name': 'Pre-break observation value',
     'values': []},
    {'id': 'OBS_COM', 'name': 'Observation comment', 'values': []}]}}}

In [166]:
import requests
session=requests.Session()
response = session.get(
                f"{"https://data-api.ecb.europa.eu/service/data"}/{"EXR"}/{"A.USD.EUR.SP00.A"}",
                params= {"startPeriod": "2025","endPeriod":"2026","format": "jsondata"},
                timeout=10)
response.raise_for_status()
response.json()

{'header': {'id': '6ca9fa0c-ca0e-4c99-ac0e-653b61a7e78e',
  'test': False,
  'prepared': '2026-09-12T22:27:59.019+02:00',
  'sender': {'id': 'ECB'}},
 'dataSets': [{'action': 'Replace',
   'validFrom': '2026-09-12T22:27:59.019+02:00',
   'series': {'0:0:0:0:0': {'attributes': [0,
      None,
      0,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      0,
      None,
      0,
      None,
      0,
      0,
      0,
      0],
     'observations': {'0': [1.1299831372549, 0, 0, None, None]}}}}],
 'structure': {'links': [{'title': 'Exchange Rates',
    'rel': 'dataflow',
    'href': 'https://data-api.ecb.europa.eu:443/service/dataflow/ECB/EXR/1.0'}],
  'name': 'Exchange Rates',
  'dimensions': {'series': [{'id': 'FREQ',
     'name': 'Frequency',
     'values': [{'id': 'A', 'name': 'Annual'}]},
    {'id': 'CURRENCY',
     'name': 'Currency',
     'values': [{'id': 'USD', 'name': 'US dollar'}]},
    {'id': 'CURRENCY_DENOM',
     'name': 'Currency denominator',
     'values': [{'id': 'EUR', 'name': 'Euro'}]},
    {'id': 'EXR_TYPE',
     'name': 'Exchange rate type',
     'values': [{'id': 'SP00', 'name': 'Spot'}]},
    {'id': 'EXR_SUFFIX',
     'name': 'Series variation - EXR context',
     'values': [{'id': 'A', 'name': 'Average'}]}],
   'observation': [{'id': 'TIME_PERIOD',
     'name': 'Time period or range',
     'role': 'time',
     'values': [{'id': '2025',
       'name': '2025',
       'start': '2025-01-01T00:00:00.000+01:00',
       'end': '2025-12-31T23:59:59.999+01:00'}]}]},
  'attributes': {'series': [{'id': 'TIME_FORMAT',
     'name': 'Time format code',
     'values': [{'name': 'P1Y'}]},
    {'id': 'BREAKS', 'name': 'Breaks', 'values': []},
    {'id': 'COLLECTION',
     'name': 'Collection indicator',
     'values': [{'id': 'A',
       'name': 'Average of observations through period'}]},
    {'id': 'COMPILING_ORG', 'name': 'Compiling organisation', 'values': []},
    {'id': 'DISS_ORG',
     'name': 'Data dissemination organisation',
     'values': []},
    {'id': 'DOM_SER_IDS', 'name': 'Domestic series ids', 'values': []},
    {'id': 'PUBL_ECB', 'name': 'Source publication (ECB only)', 'values': []},
    {'id': 'PUBL_MU',
     'name': 'Source publication (Euro area only)',
     'values': []},
    {'id': 'PUBL_PUBLIC', 'name': 'Source publication (public)', 'values': []},
    {'id': 'UNIT_INDEX_BASE', 'name': 'Unit index base', 'values': []},
    {'id': 'COMPILATION', 'name': 'Compilation', 'values': []},
    {'id': 'COVERAGE', 'name': 'Coverage', 'values': []},
    {'id': 'DECIMALS',
     'name': 'Decimals',
     'values': [{'id': '4', 'name': 'Four'}]},
    {'id': 'NAT_TITLE', 'name': 'National language title', 'values': []},
    {'id': 'SOURCE_AGENCY',
     'name': 'Source agency',
     'values': [{'id': '4F0', 'name': 'European Central Bank (ECB)'}]},
    {'id': 'SOURCE_PUB', 'name': 'Publication source', 'values': []},
    {'id': 'TITLE',
     'name': 'Title',
     'values': [{'name': 'US dollar/Euro ECB reference exchange rate'}]},
    {'id': 'TITLE_COMPL',
     'name': 'Title complement',
     'values': [{'name': 'ECB reference exchange rate, US dollar/Euro, 2.15 pm (C.E.T.)'}]},
    {'id': 'UNIT',
     'name': 'Unit',
     'values': [{'id': 'USD', 'name': 'US dollar'}]},
    {'id': 'UNIT_MULT',
     'name': 'Unit multiplier',
     'values': [{'id': '0', 'name': 'Units'}]}],
   'observation': [{'id': 'OBS_STATUS',
     'name': 'Observation status',
     'values': [{'id': 'A', 'name': 'Normal value'}]},
    {'id': 'OBS_CONF',
     'name': 'Observation confidentiality',
     'values': [{'id': 'F', 'name': 'Free'}]},
    {'id': 'OBS_PRE_BREAK',
     'name': 'Pre-break observation value',
     'values': []},
    {'id': 'OBS_COM', 'name': 'Observation comment', 'values': []}]}}}

In [167]:
import requests
session=requests.Session()
response = session.get(
                f"{"https://data-api.ecb.europa.eu/service/data"}/{"EXR"}/{"D.E02.EUR.EN00.E"}",
                params= {"startPeriod": "2026","endPeriod":"2026","format": "jsondata"},
                timeout=10)
response.raise_for_status()
response.json()

HTTPError: 404 Client Error: Not Found for url: https://data-api.ecb.europa.eu/service/data/EXR/D.E02.EUR.EN00.E?startPeriod=2026&endPeriod=2026&format=jsondata

In [ ]:
import requests
session=requests.Session()
response = session.get(
                f"{"https://data-api.ecb.europa.eu/service/data"}/{"FM"}/{"D.U2.EUR.4F.KR.MLFR.CHG"}",
                params= {"startPeriod": "2026-01-01","endPeriod":"2026-02-01","format": "jsondata"},
                timeout=10)
response.raise_for_status()
response.json()

{'header': {'id': '8ecd3a4e-5f6d-4e6c-9510-3c071e1506f6',
  'test': False,
  'prepared': '2026-09-13T00:07:26.235+02:00',
  'sender': {'id': 'ECB'}},
 'dataSets': [{'action': 'Replace',
   'validFrom': '2026-09-13T00:07:26.235+02:00',
   'series': {'0:0:0:0:0:0:0': {'attributes': [0,
      None,
      0,
      0,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      0,
      None,
      None,
      0,
      0,
      0,
      0],
     'observations': {'0': [-0.25, 0, 0, None, None],
      '1': [-0.25, 0, 0, None, None],
      '2': [-0.25, 0, 0, None, None],
      '3': [-0.25, 0, 0, None, None],
      '4': [-0.25, 0, 0, None, None],
      '5': [-0.25, 0, 0, None, None],
      '6': [-0.25, 0, 0, None, None],
      '7': [-0.25, 0, 0, None, None],
      '8': [-0.25, 0, 0, None, None],
      '9': [-0.25, 0, 0, None, None],
      '10': [-0.25, 0, 0, None, None],
      '11': [-0.25, 0, 0, None, None],
      '12': [-0.25, 0, 0, None, None],
      '13': [-0.25, 0, 0, None, None],
      '14': [-0.25, 0, 0, None, None],
      '15': [-0.25, 0, 0, None, None],
      '16': [-0.25, 0, 0, None, None],
      '17': [-0.25, 0, 0, None, None],
      '18': [-0.25, 0, 0, None, None],
      '19': [-0.25, 0, 0, None, None],
      '20': [-0.25, 0, 0, None, None],
      '21': [-0.25, 0, 0, None, None],
      '22': [-0.25, 0, 0, None, None],
      '23': [-0.25, 0, 0, None, None],
      '24': [-0.25, 0, 0, None, None],
      '25': [-0.25, 0, 0, None, None],
      '26': [-0.25, 0, 0, None, None],
      '27': [-0.25, 0, 0, None, None],
      '28': [-0.25, 0, 0, None, None],
      '29': [-0.25, 0, 0, None, None],
      '30': [-0.25, 0, 0, None, None],
      '31': [-0.25, 0, 0, None, None]}}}}],
 'structure': {'links': [{'title': 'Financial market data',
    'rel': 'dataflow',
    'href': 'https://data-api.ecb.europa.eu:443/service/dataflow/ECB/FM/1.0'}],
  'name': 'Financial market data',
  'dimensions': {'series': [{'id': 'FREQ',
     'name': 'Frequency',
     'values': [{'id': 'D', 'name': 'Daily'}]},
    {'id': 'REF_AREA',
     'name': 'Reference area',
     'values': [{'id': 'U2', 'name': 'Euro area (changing composition)'}]},
    {'id': 'CURRENCY',
     'name': 'Currency',
     'values': [{'id': 'EUR', 'name': 'Euro'}]},
    {'id': 'PROVIDER_FM',
     'name': 'Financial market provider',
     'values': [{'id': '4F', 'name': 'ECB'}]},
    {'id': 'INSTRUMENT_FM',
     'name': 'Financial market instrument',
     'values': [{'id': 'KR', 'name': 'Key interest rate'}]},
    {'id': 'PROVIDER_FM_ID',
     'name': 'Financial market provider identifier',
     'values': [{'id': 'MLFR',
       'name': 'Marginal lending facility - date of changes (raw data)'}]},
    {'id': 'DATA_TYPE_FM',
     'name': 'Financial market data type',
     'values': [{'id': 'CHG',
       'name': 'Change in percentage points compared to previous rate'}]}],
   'observation': [{'id': 'TIME_PERIOD',
     'name': 'Time period or range',
     'role': 'time',
     'values': [{'id': '2026-01-01',
       'name': '2026-01-01',
       'start': '2026-01-01T00:00:00.000+01:00',
       'end': '2026-01-01T23:59:59.999+01:00'},
      {'id': '2026-01-02',
       'name': '2026-01-02',
       'start': '2026-01-02T00:00:00.000+01:00',
       'end': '2026-01-02T23:59:59.999+01:00'},
      {'id': '2026-01-03',
       'name': '2026-01-03',
       'start': '2026-01-03T00:00:00.000+01:00',
       'end': '2026-01-03T23:59:59.999+01:00'},
      {'id': '2026-01-04',
       'name': '2026-01-04',
       'start': '2026-01-04T00:00:00.000+01:00',
       'end': '2026-01-04T23:59:59.999+01:00'},
      {'id': '2026-01-05',
       'name': '2026-01-05',
       'start': '2026-01-05T00:00:00.000+01:00',
       'end': '2026-01-05T23:59:59.999+01:00'},
      {'id': '2026-01-06',
       'name': '2026-01-06',
       'start': '2026-01-06T00:00:00.000+01:00',
       'end': '2026-01-06T23:59:59.999+01:00'},
      {'id': '2026-01-07',
       'name': '2026-01-07',
       'start': '2026-01-07T00:00:00.000+01:00',
       'end': '2026-01-07T23:59:59.999+01:00'},
      {'id': '2026-01-08',
       'name': '2026-01-08',
       'start': '2026-01-08T00:00:00.000+01:00',
       'end': '2026-01-08T23:59:59.999+01:00'},
      {'id': '2026-01-09',
       'name': '2026-01-09',
       'start': '2026-01-09T00:00:00.000+01:00',
       'end': '2026-01-09T23:59:59.999+01:00'},
      {'id': '2026-01-10',
       'name': '2026-01-10',
       'start': '2026-01-10T00:00:00.000+01:00',
       'end': '2026-01-10T23:59:59.999+01:00'},
      {'id': '2026-01-11',
       'name': '2026-01-11',
       'start': '2026-01-11T00:00:00.000+01:00',
       'end': '2026-01-11T23:59:59.999+01:00'},
      {'id': '2026-01-12',
       'name': '2026-01-12',
       'start': '2026-01-12T00:00:00.000+01:00',
       'end': '2026-01-12T23:59:59.999+01:00'},
      {'id': '2026-01-13',
       'name': '2026-01-13',
       'start': '2026-01-13T00:00:00.000+01:00',
       'end': '2026-01-13T23:59:59.999+01:00'},
      {'id': '2026-01-14',
       'name': '2026-01-14',
       'start': '2026-01-14T00:00:00.000+01:00',
       'end': '2026-01-14T23:59:59.999+01:00'},
      {'id': '2026-01-15',
       'name': '2026-01-15',
       'start': '2026-01-15T00:00:00.000+01:00',
       'end': '2026-01-15T23:59:59.999+01:00'},
      {'id': '2026-01-16',
       'name': '2026-01-16',
       'start': '2026-01-16T00:00:00.000+01:00',
       'end': '2026-01-16T23:59:59.999+01:00'},
      {'id': '2026-01-17',
       'name': '2026-01-17',
       'start': '2026-01-17T00:00:00.000+01:00',
       'end': '2026-01-17T23:59:59.999+01:00'},
      {'id': '2026-01-18',
       'name': '2026-01-18',
       'start': '2026-01-18T00:00:00.000+01:00',
       'end': '2026-01-18T23:59:59.999+01:00'},
      {'id': '2026-01-19',
       'name': '2026-01-19',
       'start': '2026-01-19T00:00:00.000+01:00',
       'end': '2026-01-19T23:59:59.999+01:00'},
      {'id': '2026-01-20',
       'name': '2026-01-20',
       'start': '2026-01-20T00:00:00.000+01:00',
       'end': '2026-01-20T23:59:59.999+01:00'},
      {'id': '2026-01-21',
       'name': '2026-01-21',
       'start': '2026-01-21T00:00:00.000+01:00',
       'end': '2026-01-21T23:59:59.999+01:00'},
      {'id': '2026-01-22',
       'name': '2026-01-22',
       'start': '2026-01-22T00:00:00.000+01:00',
       'end': '2026-01-22T23:59:59.999+01:00'},
      {'id': '2026-01-23',
       'name': '2026-01-23',
       'start': '2026-01-23T00:00:00.000+01:00',
       'end': '2026-01-23T23:59:59.999+01:00'},
      {'id': '2026-01-24',
       'name': '2026-01-24',
       'start': '2026-01-24T00:00:00.000+01:00',
       'end': '2026-01-24T23:59:59.999+01:00'},
      {'id': '2026-01-25',
       'name': '2026-01-25',
       'start': '2026-01-25T00:00:00.000+01:00',
       'end': '2026-01-25T23:59:59.999+01:00'},
      {'id': '2026-01-26',
       'name': '2026-01-26',
       'start': '2026-01-26T00:00:00.000+01:00',
       'end': '2026-01-26T23:59:59.999+01:00'},
      {'id': '2026-01-27',
       'name': '2026-01-27',
       'start': '2026-01-27T00:00:00.000+01:00',
       'end': '2026-01-27T23:59:59.999+01:00'},
      {'id': '2026-01-28',
       'name': '2026-01-28',
       'start': '2026-01-28T00:00:00.000+01:00',
       'end': '2026-01-28T23:59:59.999+01:00'},
      {'id': '2026-01-29',
       'name': '2026-01-29',
       'start': '2026-01-29T00:00:00.000+01:00',
       'end': '2026-01-29T23:59:59.999+01:00'},
      {'id': '2026-01-30',
       'name': '2026-01-30',
       'start': '2026-01-30T00:00:00.000+01:00',
       'end': '2026-01-30T23:59:59.999+01:00'},
      {'id': '2026-01-31',
       'name': '2026-01-31',
       'start': '2026-01-31T00:00:00.000+01:00',
       'end': '2026-01-31T23:59:59.999+01:00'},
      {'id': '2026-02-01',
       'name': '2026-02-01',
       'start': '2026-02-01T00:00:00.000+01:00',
       'end': '2026-02-01T23:59:59.999+01:00'}]}]},
  'attributes': {'series': [{'id': 'TIME_FORMAT',
     'name': 'Time format code',
     'values': [{'name': 'P1D'}]},
    {'id': 'BREAKS', 'name': 'Breaks', 'values': []},
    {'id': 'COLLECTION',
     'name': 'Collection indicator',
     'values': [{'id': 'E', 'name': 'End of period'}]},
    {'id': 'COMPILING_ORG',
     'name': 'Compiling organisation',
     'values': [{'id': '4F0', 'name': 'European Central Bank (ECB)'}]},
    {'id': 'DISS_ORG',
     'name': 'Data dissemination organisation',
     'values': []},
    {'id': 'DOM_SER_IDS', 'name': 'Domestic series ids', 'values': []},
    {'id': 'FM_CONTRACT_TIME',
     'name': 'Contract month/expired date',
     'values': []},
    {'id': 'FM_COUPON_RATE', 'name': 'Coupon rate of the bond', 'values': []},
    {'id': 'FM_IDENTIFIER',
     'name': 'Financial instrument Identifier',
     'values': []},
    {'id': 'FM_LOT_SIZE', 'name': 'Lot size units', 'values': []},
    {'id': 'FM_MATURITY', 'name': 'Bond maturity', 'values': []},
    {'id': 'FM_OUTS_AMOUNT', 'name': 'Outstanding amount', 'values': []},
    {'id': 'FM_PUT_CALL', 'name': 'options type', 'values': []},
    {'id': 'FM_STRIKE_PRICE',
     'name': 'Strike price of the options',
     'values': []},
    {'id': 'PUBL_MU',
     'name': 'Source publication (Euro area only)',
     'values': []},
    {'id': 'PUBL_PUBLIC', 'name': 'Source publication (public)', 'values': []},
    {'id': 'UNIT_INDEX_BASE', 'name': 'Unit index base', 'values': []},
    {'id': 'COMPILATION', 'name': 'Compilation', 'values': []},
    {'id': 'COVERAGE', 'name': 'Coverage', 'values': []},
    {'id': 'DECIMALS',
     'name': 'Decimals',
     'values': [{'id': '7', 'name': 'Seven'}]},
    {'id': 'SOURCE_AGENCY', 'name': 'Source agency', 'values': []},
    {'id': 'SOURCE_PUB', 'name': 'Publication source', 'values': []},
    {'id': 'TITLE',
     'name': 'Title',
     'values': [{'name': 'Marginal lending facility - date of changes (raw data) - Change in percentage points compared to previous rate'}]},
    {'id': 'TITLE_COMPL',
     'name': 'Title complement',
     'values': [{'name': 'Euro area (changing composition) - Key interest rate - Marginal lending facility - date of changes (raw data) - Change in percentage points compared to previous rate - Euro, provided by ECB'}]},
    {'id': 'UNIT',
     'name': 'Unit',
     'values': [{'id': 'PC', 'name': 'Percent'}]},
    {'id': 'UNIT_MULT',
     'name': 'Unit multiplier',
     'values': [{'id': '0', 'name': 'Units'}]}],
   'observation': [{'id': 'OBS_STATUS',
     'name': 'Observation status',
     'values': [{'id': 'A', 'name': 'Normal value'}]},
    {'id': 'OBS_CONF',
     'name': 'Observation confidentiality',
     'values': [{'id': 'F', 'name': 'Free'}]},
    {'id': 'OBS_PRE_BREAK',
     'name': 'Pre-break observation value',
     'values': []},
    {'id': 'OBS_COM', 'name': 'Observation comment', 'values': []}]}}}

In [174]:
import requests
session=requests.Session()
response = session.get(f"https://data-api.ecb.europa.eu/service/data/YC/B.U2.EUR.4F.G_N_C.SV_C_YM.SR_10Y",
                params= {"startPeriod": "2026","endPeriod":"2026","format": "jsondata"},
                timeout=10)
response.raise_for_status()
response.json()

{'header': {'id': '0180387b-5d6a-4507-ac17-0a2931bdceb3',
  'test': False,
  'prepared': '2026-09-13T00:33:18.721+02:00',
  'sender': {'id': 'ECB'}},
 'dataSets': [{'action': 'Replace',
   'validFrom': '2026-09-13T00:33:18.721+02:00',
   'series': {'0:0:0:0:0:0:0': {'attributes': [0,
      None,
      0,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      None,
      0,
      None,
      0,
      None,
      None,
      0,
      0,
      0,
      0],
     'observations': {'0': [3.3599492829, 0, 0, None, None],
      '1': [3.3448813122, 0, 0, None, None],
      '2': [3.3027076684, 0, 0, None, None],
      '3': [3.2889472915, 0, 0, None, None],
      '4': [3.2973846886, 0, 0, None, None],
      '5': [3.292688294, 0, 0, None, None],
      '6': [3.2666301036, 0, 0, None, None],
      '7': [3.2791600269, 0, 0, None, None],
      '8': [3.2666889166, 0, 0, None, None],
      '9': [3.2423655133, 0, 0, None, None],
      '10': [3.260574161, 0, 0, None, None],
      '11': [3.2576389478, 0, 0, None, None],
      '12': [3.2957181344, 0, 0, None, None],
      '13': [3.3087836071, 0, 0, None, None],
      '14': [3.3041466258, 0, 0, None, None],
      '15': [3.2931187339, 0, 0, None, None],
      '16': [3.2550653171, 0, 0, None, None],
      '17': [3.2671386007, 0, 0, None, None],
      '18': [3.2486149742, 0, 0, None, None],
      '19': [3.2409059103, 0, 0, None, None],
      '20': [3.2501436722, 0, 0, None, None],
      '21': [3.2602867444, 0, 0, None, None],
      '22': [3.2918717477, 0, 0, None, None],
      '23': [3.2757793037, 0, 0, None, None],
      '24': [3.2833635762, 0, 0, None, None],
      '25': [3.2601297609, 0, 0, None, None],
      '26': [3.2638584297, 0, 0, None, None],
      '27': [3.2187240482, 0, 0, None, None],
      '28': [3.2230003006, 0, 0, None, None],
      '29': [3.1997132491, 0, 0, None, None],
      '30': [3.1733065655, 0, 0, None, None],
      '31': [3.1710098866, 0, 0, None, None],
      '32': [3.1582790199, 0, 0, None, None],
      '33': [3.1514806367, 0, 0, None, None],
      '34': [3.1598294231, 0, 0, None, None],
      '35': [3.1403444115, 0, 0, None, None],
      '36': [3.1322325132, 0, 0, None, None],
      '37': [3.1215737363, 0, 0, None, None],
      '38': [3.1158207251, 0, 0, None, None],
      '39': [3.1000545384, 0, 0, None, None],
      '40': [3.09476223, 0, 0, None, None],
      '41': [3.1296083045, 0, 0, None, None],
      '42': [3.235901743, 0, 0, None, None],
      '43': [3.1958409371, 0, 0, None, None],
      '44': [3.2588722958, 0, 0, None, None],
      '45': [3.3278329181, 0, 0, None, None],
      '46': [3.3361914735, 0, 0, None, None],
      '47': [3.2672975893, 0, 0, None, None],
      '48': [3.3643416704, 0, 0, None, None],
      '49': [3.4195157665, 0, 0, None, None],
      '50': [3.4355386101, 0, 0, None, None],
      '51': [3.3968036588, 0, 0, None, None],
      '52': [3.3665157442, 0, 0, None, None],
      '53': [3.4207298464, 0, 0, None, None],
      '54': [3.4409683853, 0, 0, None, None],
      '55': [3.5314594919, 0, 0, None, None],
      '56': [3.4566210168, 0, 0, None, None],
      '57': [3.51422019, 0, 0, None, None],
      '58': [3.4499921241, 0, 0, None, None],
      '59': [3.5526384842, 0, 0, None, None],
      '60': [3.6294908127, 0, 0, None, None],
      '61': [3.5592814742, 0, 0, None, None],
      '62': [3.5104228621, 0, 0, None, None],
      '63': [3.485055913, 0, 0, None, None],
      '64': [3.521646569, 0, 0, None, None],
      '65': [3.5360097739, 0, 0, None, None],
      '66': [3.3683476853, 0, 0, None, None],
      '67': [3.4722801684, 0, 0, None, None],
      '68': [3.505578793, 0, 0, None, None],
      '69': [3.5245040456, 0, 0, None, None],
      '70': [3.5007160674, 0, 0, None, None],
      '71': [3.4887046886, 0, 0, None, None],
      '72': [3.489621851, 0, 0, None, None],
      '73': [3.4115195599, 0, 0, None, None],
      '74': [3.4275151712, 0, 0, None, None],
      '75': [3.4249166636, 0, 0, None, None],
      '76': [3.4528307176, 0, 0, None, None],
      '77': [3.4737060777, 0, 0, None, None],
      '78': [3.4825008689, 0, 0, None, None],
      '79': [3.481352228, 0, 0, None, None],
      '80': [3.5226903927, 0, 0, None, None],
      '81': [3.5556547695, 0, 0, None, None],
      '82': [3.5093658241, 0, 0, None, None],
      '83': [3.5223830977, 0, 0, None, None],
      '84': [3.5344596947, 0, 0, None, None],
      '85': [3.4195261634, 0, 0, None, None],
      '86': [3.4078656818, 0, 0, None, None],
      '87': [3.4144864513, 0, 0, None, None],
      '88': [3.4590837049, 0, 0, None, None],
      '89': [3.5322673125, 0, 0, None, None],
      '90': [3.5379551468, 0, 0, None, None],
      '91': [3.4778611943, 0, 0, None, None],
      '92': [3.5912268205, 0, 0, None, None],
      '93': [3.5558279286, 0, 0, None, None],
      '94': [3.6141217503, 0, 0, None, None],
      '95': [3.5753104657, 0, 0, None, None],
      '96': [3.5243008788, 0, 0, None, None],
      '97': [3.4653613173, 0, 0, None, None],
      '98': [3.358616107, 0, 0, None, None],
      '99': [3.4089543432, 0, 0, None, None],
      '100': [3.3926609936, 0, 0, None, None],
      '101': [3.410886167, 0, 0, None, None],
      '102': [3.380954753, 0, 0, None, None],
      '103': [3.4500913511, 0, 0, None, None],
      '104': [3.3902512388, 0, 0, None, None],
      '105': [3.4348715098, 0, 0, None, None],
      '106': [3.4511028291, 0, 0, None, None],
      '107': [3.4744139233, 0, 0, None, None],
      '108': [3.487726076, 0, 0, None, None],
      '109': [3.488063803, 0, 0, None, None],
      '110': [3.5103484856, 0, 0, None, None],
      '111': [3.4668668771, 0, 0, None, None],
      '112': [3.4551296195, 0, 0, None, None],
      '113': [3.381408222, 0, 0, None, None],
      '114': [3.3602409637, 0, 0, None, None],
      '115': [3.3523495534, 0, 0, None, None],
      '116': [3.3587991897, 0, 0, None, None],
      '117': [3.4132087871, 0, 0, None, None],
      '118': [3.3811842439, 0, 0, None, None],
      '119': [3.3456095966, 0, 0, None, None],
      '120': [3.3133041107, 0, 0, None, None],
      '121': [3.2941348793, 0, 0, None, None],
      '122': [3.3063261592, 0, 0, None, None],
      '123': [3.3096783731, 0, 0, None, None],
      '124': [3.3060242467, 0, 0, None, None],
      '125': [3.3507512672, 0, 0, None, None],
      '126': [3.3715006758, 0, 0, None, None],
      '127': [3.3901701976, 0, 0, None, None],
      '128': [3.3938655797, 0, 0, None, None],
      '129': [3.4353392101, 0, 0, None, None],
      '130': [3.529696615, 0, 0, None, None],
      '131': [3.5188504861, 0, 0, None, None],
      '132': [3.4971309591, 0, 0, None, None],
      '133': [3.5166069775, 0, 0, None, None],
      '134': [3.5444580703, 0, 0, None, None],
      '135': [3.5623777293, 0, 0, None, None],
      '136': [3.5954508208, 0, 0, None, None],
      '137': [3.5695168355, 0, 0, None, None],
      '138': [3.5814228449, 0, 0, None, None],
      '139': [3.6299876447, 0, 0, None, None],
      '140': [3.6270830064, 0, 0, None, None],
      '141': [3.6516146855, 0, 0, None, None],
      '142': [3.6257422083, 0, 0, None, None],
      '143': [3.5773415009, 0, 0, None, None],
      '144': [3.573321124, 0, 0, None, None],
      '145': [3.5929685846, 0, 0, None, None],
      '146': [3.6181984581, 0, 0, None, None],
      '147': [3.6397131405, 0, 0, None, None],
      '148': [3.5844588846, 0, 0, None, None],
      '149': [3.5363611059, 0, 0, None, None],
      '150': [3.543432092, 0, 0, None, None],
      '151': [3.5476455052, 0, 0, None, None],
      '152': [3.5535294433, 0, 0, None, None],
      '153': [3.6077139347, 0, 0, None, None],
      '154': [3.5897374548, 0, 0, None, None],
      '155': [3.5723183846, 0, 0, None, None],
      '156': [3.5681337553, 0, 0, None, None],
      '157': [3.6250413829, 0, 0, None, None],
      '158': [3.6566681992, 0, 0, None, None],
      '159': [3.7170282087, 0, 0, None, None],
      '160': [3.7003561699, 0, 0, None, None],
      '161': [3.7086939892, 0, 0, None, None],
      '162': [3.700447696, 0, 0, None, None],
      '163': [3.7161664926, 0, 0, None, None],
      '164': [3.6685076859, 0, 0, None, None],
      '165': [3.6716494885, 0, 0, None, None],
      '166': [3.702870898, 0, 0, None, None],
      '167': [3.7020901176, 0, 0, None, None],
      '168': [3.7698538257, 0, 0, None, None],
      '169': [3.7869779662, 0, 0, None, None],
      '170': [3.8249337289, 0, 0, None, None],
      '171': [3.7887590778, 0, 0, None, None],
      '172': [3.7675946677, 0, 0, None, None],
      '173': [3.8124437828, 0, 0, None, None],
      '174': [3.8033854154, 0, 0, None, None],
      '175': [3.857746608, 0, 0, None, None],
      '176': [3.9520375537, 0, 0, None, None]}}}}],
 'structure': {'links': [{'title': 'Financial market data - yield curve',
    'rel': 'dataflow',
    'href': 'https://data-api.ecb.europa.eu:443/service/dataflow/ECB/YC/1.0'}],
  'name': 'Financial market data - yield curve',
  'dimensions': {'series': [{'id': 'FREQ',
     'name': 'Frequency',
     'values': [{'id': 'B', 'name': 'Daily - businessweek'}]},
    {'id': 'REF_AREA',
     'name': 'Reference area',
     'values': [{'id': 'U2', 'name': 'Euro area (changing composition)'}]},
    {'id': 'CURRENCY',
     'name': 'Currency',
     'values': [{'id': 'EUR', 'name': 'Euro'}]},
    {'id': 'PROVIDER_FM',
     'name': 'Financial market provider',
     'values': [{'id': '4F', 'name': 'ECB'}]},
    {'id': 'INSTRUMENT_FM',
     'name': 'Financial market instrument',
     'values': [{'id': 'G_N_C',
       'name': 'Government bond, nominal, all issuers all ratings included'}]},
    {'id': 'PROVIDER_FM_ID',
     'name': 'Financial market provider identifier',
     'values': [{'id': 'SV_C_YM',
       'name': 'Svensson model - continuous compounding - yield error minimisation'}]},
    {'id': 'DATA_TYPE_FM',
     'name': 'Financial market data type',
     'values': [{'id': 'SR_10Y',
       'name': 'Yield curve spot rate, 10-year maturity'}]}],
   'observation': [{'id': 'TIME_PERIOD',
     'name': 'Time period or range',
     'role': 'time',
     'values': [{'id': '2026-01-02',
       'name': '2026-01-02',
       'start': '2026-01-02T00:00:00.000+01:00',
       'end': '2026-01-02T23:59:59.999+01:00'},
      {'id': '2026-01-05',
       'name': '2026-01-05',
       'start': '2026-01-05T00:00:00.000+01:00',
       'end': '2026-01-05T23:59:59.999+01:00'},
      {'id': '2026-01-06',
       'name': '2026-01-06',
       'start': '2026-01-06T00:00:00.000+01:00',
       'end': '2026-01-06T23:59:59.999+01:00'},
      {'id': '2026-01-07',
       'name': '2026-01-07',
       'start': '2026-01-07T00:00:00.000+01:00',
       'end': '2026-01-07T23:59:59.999+01:00'},
      {'id': '2026-01-08',
       'name': '2026-01-08',
       'start': '2026-01-08T00:00:00.000+01:00',
       'end': '2026-01-08T23:59:59.999+01:00'},
      {'id': '2026-01-09',
       'name': '2026-01-09',
       'start': '2026-01-09T00:00:00.000+01:00',
       'end': '2026-01-09T23:59:59.999+01:00'},
      {'id': '2026-01-12',
       'name': '2026-01-12',
       'start': '2026-01-12T00:00:00.000+01:00',
       'end': '2026-01-12T23:59:59.999+01:00'},
      {'id': '2026-01-13',
       'name': '2026-01-13',
       'start': '2026-01-13T00:00:00.000+01:00',
       'end': '2026-01-13T23:59:59.999+01:00'},
      {'id': '2026-01-14',
       'name': '2026-01-14',
       'start': '2026-01-14T00:00:00.000+01:00',
       'end': '2026-01-14T23:59:59.999+01:00'},
      {'id': '2026-01-15',
       'name': '2026-01-15',
       'start': '2026-01-15T00:00:00.000+01:00',
       'end': '2026-01-15T23:59:59.999+01:00'},
      {'id': '2026-01-16',
       'name': '2026-01-16',
       'start': '2026-01-16T00:00:00.000+01:00',
       'end': '2026-01-16T23:59:59.999+01:00'},
      {'id': '2026-01-19',
       'name': '2026-01-19',
       'start': '2026-01-19T00:00:00.000+01:00',
       'end': '2026-01-19T23:59:59.999+01:00'},
      {'id': '2026-01-20',
       'name': '2026-01-20',
       'start': '2026-01-20T00:00:00.000+01:00',
       'end': '2026-01-20T23:59:59.999+01:00'},
      {'id': '2026-01-21',
       'name': '2026-01-21',
       'start': '2026-01-21T00:00:00.000+01:00',
       'end': '2026-01-21T23:59:59.999+01:00'},
      {'id': '2026-01-22',
       'name': '2026-01-22',
       'start': '2026-01-22T00:00:00.000+01:00',
       'end': '2026-01-22T23:59:59.999+01:00'},
      {'id': '2026-01-23',
       'name': '2026-01-23',
       'start': '2026-01-23T00:00:00.000+01:00',
       'end': '2026-01-23T23:59:59.999+01:00'},
      {'id': '2026-01-26',
       'name': '2026-01-26',
       'start': '2026-01-26T00:00:00.000+01:00',
       'end': '2026-01-26T23:59:59.999+01:00'},
      {'id': '2026-01-27',
       'name': '2026-01-27',
       'start': '2026-01-27T00:00:00.000+01:00',
       'end': '2026-01-27T23:59:59.999+01:00'},
      {'id': '2026-01-28',
       'name': '2026-01-28',
       'start': '2026-01-28T00:00:00.000+01:00',
       'end': '2026-01-28T23:59:59.999+01:00'},
      {'id': '2026-01-29',
       'name': '2026-01-29',
       'start': '2026-01-29T00:00:00.000+01:00',
       'end': '2026-01-29T23:59:59.999+01:00'},
      {'id': '2026-01-30',
       'name': '2026-01-30',
       'start': '2026-01-30T00:00:00.000+01:00',
       'end': '2026-01-30T23:59:59.999+01:00'},
      {'id': '2026-02-02',
       'name': '2026-02-02',
       'start': '2026-02-02T00:00:00.000+01:00',
       'end': '2026-02-02T23:59:59.999+01:00'},
      {'id': '2026-02-03',
       'name': '2026-02-03',
       'start': '2026-02-03T00:00:00.000+01:00',
       'end': '2026-02-03T23:59:59.999+01:00'},
      {'id': '2026-02-04',
       'name': '2026-02-04',
       'start': '2026-02-04T00:00:00.000+01:00',
       'end': '2026-02-04T23:59:59.999+01:00'},
      {'id': '2026-02-05',
       'name': '2026-02-05',
       'start': '2026-02-05T00:00:00.000+01:00',
       'end': '2026-02-05T23:59:59.999+01:00'},
      {'id': '2026-02-06',
       'name': '2026-02-06',
       'start': '2026-02-06T00:00:00.000+01:00',
       'end': '2026-02-06T23:59:59.999+01:00'},
      {'id': '2026-02-09',
       'name': '2026-02-09',
       'start': '2026-02-09T00:00:00.000+01:00',
       'end': '2026-02-09T23:59:59.999+01:00'},
      {'id': '2026-02-10',
       'name': '2026-02-10',
       'start': '2026-02-10T00:00:00.000+01:00',
       'end': '2026-02-10T23:59:59.999+01:00'},
      {'id': '2026-02-11',
       'name': '2026-02-11',
       'start': '2026-02-11T00:00:00.000+01:00',
       'end': '2026-02-11T23:59:59.999+01:00'},
      {'id': '2026-02-12',
       'name': '2026-02-12',
       'start': '2026-02-12T00:00:00.000+01:00',
       'end': '2026-02-12T23:59:59.999+01:00'},
      {'id': '2026-02-13',
       'name': '2026-02-13',
       'start': '2026-02-13T00:00:00.000+01:00',
       'end': '2026-02-13T23:59:59.999+01:00'},
      {'id': '2026-02-16',
       'name': '2026-02-16',
       'start': '2026-02-16T00:00:00.000+01:00',
       'end': '2026-02-16T23:59:59.999+01:00'},
      {'id': '2026-02-17',
       'name': '2026-02-17',
       'start': '2026-02-17T00:00:00.000+01:00',
       'end': '2026-02-17T23:59:59.999+01:00'},
      {'id': '2026-02-18',
       'name': '2026-02-18',
       'start': '2026-02-18T00:00:00.000+01:00',
       'end': '2026-02-18T23:59:59.999+01:00'},
      {'id': '2026-02-19',
       'name': '2026-02-19',
       'start': '2026-02-19T00:00:00.000+01:00',
       'end': '2026-02-19T23:59:59.999+01:00'},
      {'id': '2026-02-20',
       'name': '2026-02-20',
       'start': '2026-02-20T00:00:00.000+01:00',
       'end': '2026-02-20T23:59:59.999+01:00'},
      {'id': '2026-02-23',
       'name': '2026-02-23',
       'start': '2026-02-23T00:00:00.000+01:00',
       'end': '2026-02-23T23:59:59.999+01:00'},
      {'id': '2026-02-24',
       'name': '2026-02-24',
       'start': '2026-02-24T00:00:00.000+01:00',
       'end': '2026-02-24T23:59:59.999+01:00'},
      {'id': '2026-02-25',
       'name': '2026-02-25',
       'start': '2026-02-25T00:00:00.000+01:00',
       'end': '2026-02-25T23:59:59.999+01:00'},
      {'id': '2026-02-26',
       'name': '2026-02-26',
       'start': '2026-02-26T00:00:00.000+01:00',
       'end': '2026-02-26T23:59:59.999+01:00'},
      {'id': '2026-02-27',
       'name': '2026-02-27',
       'start': '2026-02-27T00:00:00.000+01:00',
       'end': '2026-02-27T23:59:59.999+01:00'},
      {'id': '2026-03-02',
       'name': '2026-03-02',
       'start': '2026-03-02T00:00:00.000+01:00',
       'end': '2026-03-02T23:59:59.999+01:00'},
      {'id': '2026-03-03',
       'name': '2026-03-03',
       'start': '2026-03-03T00:00:00.000+01:00',
       'end': '2026-03-03T23:59:59.999+01:00'},
      {'id': '2026-03-04',
       'name': '2026-03-04',
       'start': '2026-03-04T00:00:00.000+01:00',
       'end': '2026-03-04T23:59:59.999+01:00'},
      {'id': '2026-03-05',
       'name': '2026-03-05',
       'start': '2026-03-05T00:00:00.000+01:00',
       'end': '2026-03-05T23:59:59.999+01:00'},
      {'id': '2026-03-06',
       'name': '2026-03-06',
       'start': '2026-03-06T00:00:00.000+01:00',
       'end': '2026-03-06T23:59:59.999+01:00'},
      {'id': '2026-03-09',
       'name': '2026-03-09',
       'start': '2026-03-09T00:00:00.000+01:00',
       'end': '2026-03-09T23:59:59.999+01:00'},
      {'id': '2026-03-10',
       'name': '2026-03-10',
       'start': '2026-03-10T00:00:00.000+01:00',
       'end': '2026-03-10T23:59:59.999+01:00'},
      {'id': '2026-03-11',
       'name': '2026-03-11',
       'start': '2026-03-11T00:00:00.000+01:00',
       'end': '2026-03-11T23:59:59.999+01:00'},
      {'id': '2026-03-12',
       'name': '2026-03-12',
       'start': '2026-03-12T00:00:00.000+01:00',
       'end': '2026-03-12T23:59:59.999+01:00'},
      {'id': '2026-03-13',
       'name': '2026-03-13',
       'start': '2026-03-13T00:00:00.000+01:00',
       'end': '2026-03-13T23:59:59.999+01:00'},
      {'id': '2026-03-16',
       'name': '2026-03-16',
       'start': '2026-03-16T00:00:00.000+01:00',
       'end': '2026-03-16T23:59:59.999+01:00'},
      {'id': '2026-03-17',
       'name': '2026-03-17',
       'start': '2026-03-17T00:00:00.000+01:00',
       'end': '2026-03-17T23:59:59.999+01:00'},
      {'id': '2026-03-18',
       'name': '2026-03-18',
       'start': '2026-03-18T00:00:00.000+01:00',
       'end': '2026-03-18T23:59:59.999+01:00'},
      {'id': '2026-03-19',
       'name': '2026-03-19',
       'start': '2026-03-19T00:00:00.000+01:00',
       'end': '2026-03-19T23:59:59.999+01:00'},
      {'id': '2026-03-20',
       'name': '2026-03-20',
       'start': '2026-03-20T00:00:00.000+01:00',
       'end': '2026-03-20T23:59:59.999+01:00'},
      {'id': '2026-03-23',
       'name': '2026-03-23',
       'start': '2026-03-23T00:00:00.000+01:00',
       'end': '2026-03-23T23:59:59.999+01:00'},
      {'id': '2026-03-24',
       'name': '2026-03-24',
       'start': '2026-03-24T00:00:00.000+01:00',
       'end': '2026-03-24T23:59:59.999+01:00'},
      {'id': '2026-03-25',
       'name': '2026-03-25',
       'start': '2026-03-25T00:00:00.000+01:00',
       'end': '2026-03-25T23:59:59.999+01:00'},
      {'id': '2026-03-26',
       'name': '2026-03-26',
       'start': '2026-03-26T00:00:00.000+01:00',
       'end': '2026-03-26T23:59:59.999+01:00'},
      {'id': '2026-03-27',
       'name': '2026-03-27',
       'start': '2026-03-27T00:00:00.000+01:00',
       'end': '2026-03-27T23:59:59.999+01:00'},
      {'id': '2026-03-30',
       'name': '2026-03-30',
       'start': '2026-03-30T00:00:00.000+02:00',
       'end': '2026-03-30T23:59:59.999+02:00'},
      {'id': '2026-03-31',
       'name': '2026-03-31',
       'start': '2026-03-31T00:00:00.000+02:00',
       'end': '2026-03-31T23:59:59.999+02:00'},
      {'id': '2026-04-01',
       'name': '2026-04-01',
       'start': '2026-04-01T00:00:00.000+02:00',
       'end': '2026-04-01T23:59:59.999+02:00'},
      {'id': '2026-04-02',
       'name': '2026-04-02',

In [50]:
import finnhub
finnhub_client = finnhub.Client(api_key="d9nl19pr01qvumgao6n0d9nl19pr01qvumgao6ng")

print(finnhub_client.stock_lobbying("AAPL", "2021-01-01", "2022-06-15"))

{'data': [{'symbol': 'AAPL', 'name': 'APPLE INC', 'description': '', 'country': 'US', 'year': 2020, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/cad6db2f-c3ca-4b9d-bc24-4c56fc7eaadb/print/', 'income': None, 'expenses': 1450000, 'postedName': '', 'date': '', 'clientId': '103979', 'registrantId': '4152', 'senateId': '4152-103979', 'houseRegistrantId': '31450'}, {'symbol': 'AAPL', 'name': 'APPLE INC', 'description': '', 'country': 'US', 'year': 2021, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/931b23da-8021-4f33-8f4b-70e571dba9b8/print/', 'income': None, 'expenses': 1460000, 'postedName': '', 'date': '', 'clientId': '103979', 'registrantId': '4152', 'senateId': '4152-103979', 'houseRegistrantId': '31450'}, {'symbol': 'AAPL', 'name': 'APPLE INC', 'description': '', 'country': 'US', 'year': 2021, 'period': 'Q2', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/008a3286-d6d5-4601-afe3-f4c4361785fc/print/', 'income': None, 'expenses': 1640000, 'postedName': '', 'date': '', 'clientId': '103979', 'registrantId': '4152', 'senateId': '4152-103979', 'houseRegistrantId': '31450'}, {'symbol': 'AAPL', 'name': 'APPLE INC', 'description': '', 'country': 'US', 'year': 2021, 'period': 'Q3', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/6a83a46f-8de5-4131-a4da-4c5ec41f18e6/print/', 'income': None, 'expenses': 1540000, 'postedName': '', 'date': '', 'clientId': '103979', 'registrantId': '4152', 'senateId': '4152-103979', 'houseRegistrantId': '31450'}, {'symbol': 'AAPL', 'name': 'APPLE INC', 'description': '', 'country': 'US', 'year': 2021, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/2b35a04d-233b-4a96-ab31-e3ae77706c51/print/', 'income': None, 'expenses': 1860000, 'postedName': '', 'date': '', 'clientId': '103979', 'registrantId': '4152', 'senateId': '4152-103979', 'houseRegistrantId': '31450'}, {'symbol': 'AAPL', 'name': 'APPLE INC', 'description': '', 'country': 'US', 'year': 2022, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/7081db47-fc7f-4c5a-a7de-f7e5d2b103b3/print/', 'income': None, 'expenses': 2500000, 'postedName': '', 'date': '', 'clientId': '103979', 'registrantId': '4152', 'senateId': '4152-103979', 'houseRegistrantId': '31450'}, {'symbol': 'AAPL', 'name': 'APPLE', 'description': '', 'country': 'US', 'year': 2020, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/2f77dc7c-c45f-4d54-bf2c-bb1841f844eb/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '162939', 'registrantId': '65976', 'senateId': '65976-162939', 'houseRegistrantId': '35617'}, {'symbol': 'AAPL', 'name': 'APPLE', 'description': '', 'country': 'US', 'year': 2021, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/848d09a2-a903-4b4f-a5be-34e6297f3a3b/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '162939', 'registrantId': '65976', 'senateId': '65976-162939', 'houseRegistrantId': '35617'}, {'symbol': 'AAPL', 'name': 'APPLE', 'description': '', 'country': 'US', 'year': 2021, 'period': 'Q2', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/928b8127-9774-4a5c-a351-a30a6b16d29b/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '162939', 'registrantId': '65976', 'senateId': '65976-162939', 'houseRegistrantId': '35617'}, {'symbol': 'AAPL', 'name': 'APPLE', 'description': '', 'country': 'US', 'year': 2021, 'period': 'Q3', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/01385422-2ae8-4293-bf83-c53a6701bd3e/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '162939', 'registrantId': '65976', 'senateId': '65976-162939', 'houseRegistrantId': '35617'}, {'symbol': 'AAPL', 'name': 'APPLE', 'description': '', 'country': 'US', 'year': 2021, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/78af9145-de01-4562-b4e7-bae5f665b6e7/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '162939', 'registrantId': '65976', 'senateId': '65976-162939', 'houseRegistrantId': '35617'}, {'symbol': 'AAPL', 'name': 'APPLE', 'description': '', 'country': 'US', 'year': 2022, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/24cd3333-b0dd-4110-b466-8930e66fadfe/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '162939', 'registrantId': '65976', 'senateId': '65976-162939', 'houseRegistrantId': '35617'}, {'symbol': 'AAPL', 'name': 'APPLE, INC.', 'description': 'Hardware and software maunfacturer', 'country': 'US', 'year': 2020, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/db75bb6f-162a-433a-a997-a679eb4c6af6/print/', 'income': 40000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '173094', 'registrantId': '86196', 'senateId': '86196-173094', 'houseRegistrantId': '36548'}, {'symbol': 'AAPL', 'name': 'APPLE, INC.', 'description': 'Hardware and software maunfacturer', 'country': 'US', 'year': 2021, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/b5515d9c-2531-434d-b391-d9f65ffdb86c/print/', 'income': 40000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '173094', 'registrantId': '86196', 'senateId': '86196-173094', 'houseRegistrantId': '36548'}, {'symbol': 'AAPL', 'name': 'APPLE, INC.', 'description': 'Hardware and software maunfacturer', 'country': 'US', 'year': 2021, 'period': 'Q2', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/10ef8ef8-aa7b-4273-8a41-3ad1147f23c8/print/', 'income': 40000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '173094', 'registrantId': '86196', 'senateId': '86196-173094', 'houseRegistrantId': '36548'}, {'symbol': 'AAPL', 'name': 'APPLE, INC.', 'description': 'Hardware and software maunfacturer', 'country': 'US', 'year': 2021, 'period': 'Q3', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/53102db9-8b66-40b3-8bd3-1c3423cf0756/print/', 'income': 40000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '173094', 'registrantId': '86196', 'senateId': '86196-173094', 'houseRegistrantId': '36548'}, {'symbol': 'AAPL', 'name': 'APPLE, INC.', 'description': 'Hardware and software maunfacturer', 'country': 'US', 'year': 2021, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/c0fa0375-524e-4bcc-8578-3e3b60286a59/print/', 'income': 40000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '173094', 'registrantId': '86196', 'senateId': '86196-173094', 'houseRegistrantId': '36548'}, {'symbol': 'AAPL', 'name': 'APPLE, INC.', 'description': 'Hardware and software maunfacturer', 'country': 'US', 'year': 2022, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/be5c455c-330d-4bb6-a3a8-d4ce688a3a69/print/', 'income': 40000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '173094', 'registrantId': '86196', 'senateId': '86196-173094', 'houseRegistrantId': '36548'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software, and online services.', 'country': 'US', 'year': 2020, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/96e719e1-cd29-48a8-b782-7d99920ed95e/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '184947', 'registrantId': '314237', 'senateId': '314237-184947', 'houseRegistrantId': '39145'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software, and online services.', 'country': 'US', 'year': 2021, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/bb275d29-c35a-4fd9-be41-ee13410c3dec/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '184947', 'registrantId': '314237', 'senateId': '314237-184947', 'houseRegistrantId': '39145'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software, and online services.', 'country': 'US', 'year': 2021, 'period': 'Q2', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/79c53e8b-de7c-4ebe-86af-dfad43fbd401/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '184947', 'registrantId': '314237', 'senateId': '314237-184947', 'houseRegistrantId': '39145'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software, and online services.', 'country': 'US', 'year': 2021, 'period': 'Q3', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/d693da16-c4d4-4640-8515-9493e7da84c1/print/', 'income': 110000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '184947', 'registrantId': '314237', 'senateId': '314237-184947', 'houseRegistrantId': '39145'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software, and online services.', 'country': 'US', 'year': 2021, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/b4b54ad4-a82a-40ee-a03b-27b2fd04582e/print/', 'income': 120000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '184947', 'registrantId': '314237', 'senateId': '314237-184947', 'houseRegistrantId': '39145'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software, and online services.', 'country': 'US', 'year': 2022, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/394b7ff4-a683-4834-b491-b72a11f9cf4b/print/', 'income': 120000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '184947', 'registrantId': '314237', 'senateId': '314237-184947', 'houseRegistrantId': '39145'}, {'symbol': 'AAPL', 'name': 'APPLE INC', 'description': '', 'country': 'US', 'year': 2020, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/96b6c830-0a84-4e38-bc01-6d1b5055f615/print/', 'income': 60000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '187732', 'registrantId': '40013096', 'senateId': '40013096-187732', 'houseRegistrantId': '39840'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer Electronics, Computer Software, Personal Computers', 'country': 'US', 'year': 2020, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/8206b60a-d567-43f9-957d-9df4ab5870f8/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '199154', 'registrantId': '401103500', 'senateId': '401103500-199154', 'houseRegistrantId': '401103500'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer Electronics, Computer Software, Personal Computers', 'country': 'US', 'year': 2021, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/718b1de1-9cf6-4954-ab50-27ce1859a439/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '199154', 'registrantId': '401103500', 'senateId': '401103500-199154', 'houseRegistrantId': '401103500'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer Electronics, Computer Software, Personal Computers', 'country': 'US', 'year': 2021, 'period': 'Q2', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/d0a434a6-4218-45c8-b80d-842f9b82d80a/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '199154', 'registrantId': '401103500', 'senateId': '401103500-199154', 'houseRegistrantId': '401103500'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer Electronics, Computer Software, Personal Computers', 'country': 'US', 'year': 2021, 'period': 'Q3', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/55d67448-3d6f-4f90-980e-705050d40039/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '199154', 'registrantId': '401103500', 'senateId': '401103500-199154', 'houseRegistrantId': '401103500'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer Electronics, Computer Software, Personal Computers', 'country': 'US', 'year': 2021, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/fbe86305-c872-4e43-8857-0c70fa86ba01/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '199154', 'registrantId': '401103500', 'senateId': '401103500-199154', 'houseRegistrantId': '401103500'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer Electronics, Computer Software, Personal Computers', 'country': 'US', 'year': 2022, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/fbfae430-a4ce-41e8-a79d-bd519454344d/print/', 'income': 90000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '199154', 'registrantId': '401103500', 'senateId': '401103500-199154', 'houseRegistrantId': '401103500'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Technology company', 'country': 'US', 'year': 2020, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/3cbb124f-4c67-4b61-91b7-a206bd642603/print/', 'income': 110000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '201409', 'registrantId': '401104313', 'senateId': '401104313-201409', 'houseRegistrantId': '401104313'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Technology company', 'country': 'US', 'year': 2021, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/a4c82bdd-4c4e-4191-a863-394ad48a64a9/print/', 'income': 110000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '201409', 'registrantId': '401104313', 'senateId': '401104313-201409', 'houseRegistrantId': '401104313'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Technology company', 'country': 'US', 'year': 2021, 'period': 'Q2', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/552c23fb-2c9f-40b3-bde1-587a8ab4cf94/print/', 'income': 110000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '201409', 'registrantId': '401104313', 'senateId': '401104313-201409', 'houseRegistrantId': '401104313'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Technology company', 'country': 'US', 'year': 2021, 'period': 'Q3', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/4b019c45-9d16-4dc9-aa79-a17c089b2cbf/print/', 'income': 110000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '201409', 'registrantId': '401104313', 'senateId': '401104313-201409', 'houseRegistrantId': '401104313'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Technology company', 'country': 'US', 'year': 2022, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/3bfe2f14-ea5d-4604-9884-b796e1649d5d/print/', 'income': 110000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '201409', 'registrantId': '401104313', 'senateId': '401104313-201409', 'houseRegistrantId': '401104313'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software and online services', 'country': 'US', 'year': 2020, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/38920440-ea5c-4024-9347-d9e63f6a8e70/print/', 'income': 30000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '207089', 'registrantId': '401105514', 'senateId': '401105514-207089', 'houseRegistrantId': '401105514'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software and online services', 'country': 'US', 'year': 2021, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/ab953fb6-0665-4ca5-9e2e-92897736b7f0/print/', 'income': 30000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '207089', 'registrantId': '401105514', 'senateId': '401105514-207089', 'houseRegistrantId': '401105514'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software and online services', 'country': 'US', 'year': 2021, 'period': 'Q2', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/ba955a45-68c7-45a0-b3a4-e92d77480574/print/', 'income': 30000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '207089', 'registrantId': '401105514', 'senateId': '401105514-207089', 'houseRegistrantId': '401105514'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software and online services', 'country': 'US', 'year': 2021, 'period': 'Q3', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/210ccea7-5075-4c7c-aec8-0ff97251b232/print/', 'income': 40000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '207089', 'registrantId': '401105514', 'senateId': '401105514-207089', 'houseRegistrantId': '401105514'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software and online services', 'country': 'US', 'year': 2021, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/e8b1bb31-1820-48ec-a4e4-9d701290d0f7/print/', 'income': 60000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '207089', 'registrantId': '401105514', 'senateId': '401105514-207089', 'houseRegistrantId': '401105514'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': 'Consumer electronics, software and online services', 'country': 'US', 'year': 2022, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/6db662fe-11ef-4098-a83e-fa3d07279b3e/print/', 'income': 60000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '207089', 'registrantId': '401105514', 'senateId': '401105514-207089', 'houseRegistrantId': '401105514'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': '&#226;€‹Consumer electronics, software, and online services', 'country': 'US', 'year': 2021, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/cb7c60d6-8f43-4987-be4b-a6484a8086f7/print/', 'income': 20000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '208525', 'registrantId': '401036920', 'senateId': '401036920-208525', 'houseRegistrantId': '401036920'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': '&#226;€‹Consumer electronics, software, and online services', 'country': 'US', 'year': 2021, 'period': 'Q2', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/4be7fa57-cc97-4f8b-8859-ae1305dd8302/print/', 'income': 30000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '208525', 'registrantId': '401036920', 'senateId': '401036920-208525', 'houseRegistrantId': '401036920'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': '&#226;€‹Consumer electronics, software, and online services', 'country': 'US', 'year': 2021, 'period': 'Q3', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/dfca23cd-9b86-4476-bed4-4a8fe6e19e08/print/', 'income': 30000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '208525', 'registrantId': '401036920', 'senateId': '401036920-208525', 'houseRegistrantId': '401036920'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': '&#226;€‹Consumer electronics, software, and online services', 'country': 'US', 'year': 2021, 'period': 'Q4', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/9601e083-a1c9-4377-b5f9-dc79593590cd/print/', 'income': 30000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '208525', 'registrantId': '401036920', 'senateId': '401036920-208525', 'houseRegistrantId': '401036920'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': '&#226;€‹Consumer electronics, software, and online services', 'country': 'US', 'year': 2022, 'period': 'Q1', 'documentUrl': 'https://lda.senate.gov/filings/public/filing/0a33f793-629a-4bb9-8611-596373998088/print/', 'income': 30000, 'expenses': None, 'postedName': '', 'date': '', 'clientId': '208525', 'registrantId': '401036920', 'senateId': '401036920-208525', 'houseRegistrantId': '401036920'}, {'symbol': 'AAPL', 'name': 'APPLE INC.', 'description': '&#226;€‹&#226;€‹Consumer

In [ ]:
"https://finnhub.io/api/v1/stock/usa-spending?symbol=AAPL&from=2021-01-01&to=2022-12-31"